# Generated by Django 5.2.6 on 2025-09-16 22:38

import django.db.models.deletion
import django.utils.timezone
import youthprofiling.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', youthprofiling.models.EncryptedField(default='', max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'verbose_name_plural': 'OTP Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YouthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', youthprofiling.models.EncryptedField(max_length=100)),
                ('last_name', youthprofiling.models.EncryptedField(max_length=100)),
                ('middle_name', youthprofiling.models.EncryptedField(blank=True, max_length=100, null=True)),
                ('suffix', youthprofiling.models.EncryptedField(blank=True, max_length=10, null=True)),
                ('address', youthprofiling.models.EncryptedField(max_length=255)),
                ('purok_zone', models.CharField(choices=[('Zone 1', 'Zone 1'), ('Zone 2', 'Zone 2'), ('Zone 3', 'Zone 3'), ('Zone 4', 'Zone 4')], default='Zone 1', max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('birthdate', youthprofiling.models.EncryptedField(max_length=10)),
                ('age', models.PositiveIntegerField(default=0)),
                ('contact_number', youthprofiling.models.EncryptedField(max_length=15)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], default='Single', max_length=10)),
                ('age_group', models.CharField(choices=[('15-17', '15-17 years'), ('18-21', '18-21 years'), ('22-25', '22-25 years'), ('26-30', '26-30 years')], default='15-17', max_length=10)),
                ('education', models.CharField(choices=[('Elementary', 'Elementary'), ('High School', 'High School'), ('College', 'College'), ('Vocational', 'Vocational/Tech'), ('Postgraduate', 'Postgraduate')], default='High School', max_length=20)),
                ('youth_classification', models.CharField(choices=[('Student', 'Student'), ('Working', 'Working'), ('Out-of-School', 'Out-of-School Youth'), ('NEET', 'Not in Education, Employment or Training')], default='Student', max_length=20)),
                ('work_status', models.CharField(choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Self-Employed', 'Self-Employed'), ('Student', 'Student')], default='Student', max_length=15)),
                ('sk_voter', models.BooleanField(default=False)),
                ('registration_no', models.CharField(max_length=20, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('id_type', models.CharField(choices=[('Passport', 'Passport'), ("Driver's License", "Driver's License"), ('UMID', 'Unified Multi-Purpose ID'), ('Student ID', 'Student ID'), ('Postal ID', 'Postal ID'), ('PhilHealth ID', 'PhilHealth ID'), ('SSS ID', 'SSS ID'), ('PRC ID', 'PRC ID'), ("Voter's ID", "Voter's ID"), ('Senior Citizen ID', 'Senior Citizen ID'), ('Other', 'Other Government ID')], default='Student ID', max_length=50)),
                ('id_picture', models.ImageField(upload_to='id_pictures/')),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='birth_certificates/')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_verification_date', models.DateTimeField(blank=True, null=True)),
                ('is_admin_verified', models.BooleanField(default=False)),
                ('admin_verification_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Youth User',
                'verbose_name_plural': 'Youth Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VIEW', 'View Encrypted Data'), ('UPDATE', 'Update Encrypted Data'), ('DECRYPT', 'Decrypt Data')], default='VIEW', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('youth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youthprofiling.youthuser')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
