# Generated by Django 5.2.6 on 2025-10-25 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='allowed_age_groups',
        ),
        migrations.RemoveField(
            model_name='event',
            name='allowed_civil_statuses',
        ),
        migrations.RemoveField(
            model_name='event',
            name='allowed_education_levels',
        ),
        migrations.RemoveField(
            model_name='event',
            name='allowed_genders',
        ),
        migrations.RemoveField(
            model_name='event',
            name='allowed_work_statuses',
        ),
        migrations.RemoveField(
            model_name='event',
            name='allowed_youth_classifications',
        ),
        migrations.AddField(
            model_name='event',
            name='target_age_groups',
            field=models.ManyToManyField(blank=True, to='youthprofiling.agegroup'),
        ),
        migrations.AddField(
            model_name='event',
            name='target_civil_statuses',
            field=models.ManyToManyField(blank=True, to='youthprofiling.civilstatus'),
        ),
        migrations.AddField(
            model_name='event',
            name='target_education_levels',
            field=models.ManyToManyField(blank=True, to='youthprofiling.educationlevel'),
        ),
        migrations.AddField(
            model_name='event',
            name='target_genders',
            field=models.ManyToManyField(blank=True, to='youthprofiling.gender'),
        ),
        migrations.AddField(
            model_name='event',
            name='target_work_statuses',
            field=models.ManyToManyField(blank=True, to='youthprofiling.workstatus'),
        ),
        migrations.AddField(
            model_name='event',
            name='target_youth_classifications',
            field=models.ManyToManyField(blank=True, to='youthprofiling.youthclassification'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youthprofiling.youthadmin'),
        ),
    ]
