# Generated by Django 5.2.6 on 2025-09-17 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(choices=[('important', 'Important'), ('sports', 'Sports'), ('education', 'Education'), ('environment', 'Environment'), ('health', 'Health'), ('general', 'General')], default='general', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_important', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_age_group', models.ForeignKey(blank=True, limit_choices_to={'age_group__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='age_group_announcements', to='youthprofiling.youthuser')),
                ('target_civil_status', models.ForeignKey(blank=True, limit_choices_to={'civil_status__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civil_status_announcements', to='youthprofiling.youthuser')),
                ('target_education', models.ForeignKey(blank=True, limit_choices_to={'education__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_announcements', to='youthprofiling.youthuser')),
                ('target_gender', models.ForeignKey(blank=True, limit_choices_to={'gender__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gender_announcements', to='youthprofiling.youthuser')),
                ('target_work_status', models.ForeignKey(blank=True, limit_choices_to={'work_status__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_status_announcements', to='youthprofiling.youthuser')),
                ('target_youth_classification', models.ForeignKey(blank=True, limit_choices_to={'youth_classification__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youth_classification_announcements', to='youthprofiling.youthuser')),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(choices=[('sports', 'Sports'), ('education', 'Education'), ('health', 'Health'), ('community', 'Community'), ('cultural', 'Cultural'), ('environment', 'Environment')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('maximum_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('current_participants', models.PositiveIntegerField(default=0)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_registration', models.BooleanField(default=False)),
                ('age_min', models.PositiveIntegerField(blank=True, null=True)),
                ('age_max', models.PositiveIntegerField(blank=True, null=True)),
                ('points_reward', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_age_group', models.ForeignKey(blank=True, limit_choices_to={'age_group__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='age_group_events', to='youthprofiling.youthuser')),
                ('target_civil_status', models.ForeignKey(blank=True, limit_choices_to={'civil_status__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civil_status_events', to='youthprofiling.youthuser')),
                ('target_education', models.ForeignKey(blank=True, limit_choices_to={'education__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_events', to='youthprofiling.youthuser')),
                ('target_gender', models.ForeignKey(blank=True, limit_choices_to={'gender__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gender_events', to='youthprofiling.youthuser')),
                ('target_work_status', models.ForeignKey(blank=True, limit_choices_to={'work_status__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_status_events', to='youthprofiling.youthuser')),
                ('target_youth_classification', models.ForeignKey(blank=True, limit_choices_to={'youth_classification__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youth_classification_events', to='youthprofiling.youthuser')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('saved', 'Saved'), ('attending', 'Plan to Attend'), ('applied', 'Application Started'), ('volunteered', 'Volunteered')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youthprofiling.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youthprofiling.youthuser')),
            ],
            options={
                'unique_together': {('announcement', 'user', 'interaction_type')},
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('attendance_status', models.BooleanField(default=False)),
                ('points_awarded', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youthprofiling.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youthprofiling.youthuser')),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
    ]
