# Generated by Django 5.2.6 on 2025-11-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0002_restore_original_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthuser',
            name='shown_modals',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
