# Generated by Django 5.2.6 on 2025-09-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0002_announcement_event_announcementinteraction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('min_age', models.PositiveIntegerField()),
                ('max_age', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CivilStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouthClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='target_age_group',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='target_civil_status',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='target_education',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='target_gender',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='target_work_status',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='target_youth_classification',
        ),
        migrations.RemoveField(
            model_name='event',
            name='target_age_group',
        ),
        migrations.RemoveField(
            model_name='event',
            name='target_civil_status',
        ),
        migrations.RemoveField(
            model_name='event',
            name='target_education',
        ),
        migrations.RemoveField(
            model_name='event',
            name='target_gender',
        ),
        migrations.RemoveField(
            model_name='event',
            name='target_work_status',
        ),
        migrations.RemoveField(
            model_name='event',
            name='target_youth_classification',
        ),
        migrations.AddField(
            model_name='event',
            name='age_group_access',
            field=models.CharField(choices=[('all', 'Everyone in this group can join'), ('none', 'Nobody in this group can join'), ('specific', 'Specific selection only')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='civil_status_access',
            field=models.CharField(choices=[('all', 'Everyone in this group can join'), ('none', 'Nobody in this group can join'), ('specific', 'Specific selection only')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='education_access',
            field=models.CharField(choices=[('all', 'Everyone in this group can join'), ('none', 'Nobody in this group can join'), ('specific', 'Specific selection only')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='gender_access',
            field=models.CharField(choices=[('all', 'Everyone in this group can join'), ('none', 'Nobody in this group can join'), ('specific', 'Specific selection only')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='work_status_access',
            field=models.CharField(choices=[('all', 'Everyone in this group can join'), ('none', 'Nobody in this group can join'), ('specific', 'Specific selection only')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='youth_classification_access',
            field=models.CharField(choices=[('all', 'Everyone in this group can join'), ('none', 'Nobody in this group can join'), ('specific', 'Specific selection only')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='target_age_groups',
            field=models.ManyToManyField(blank=True, to='youthprofiling.agegroup'),
        ),
        migrations.AddField(
            model_name='event',
            name='target_civil_statuses',
            field=models.ManyToManyField(blank=True, to='youthprofiling.civilstatus'),
        ),
        migrations.AddField(
            model_name='event',
            name='target_education_levels',
            field=models.ManyToManyField(blank=True, to='youthprofiling.educationlevel'),
        ),
        migrations.AddField(
            model_name='event',
            name='target_genders',
            field=models.ManyToManyField(blank=True, to='youthprofiling.gender'),
        ),
        migrations.AddField(
            model_name='event',
            name='target_work_statuses',
            field=models.ManyToManyField(blank=True, to='youthprofiling.workstatus'),
        ),
        migrations.AddField(
            model_name='event',
            name='target_youth_classifications',
            field=models.ManyToManyField(blank=True, to='youthprofiling.youthclassification'),
        ),
    ]
