# Generated by Django 5.2.6 on 2025-09-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0003_agegroup_civilstatus_educationlevel_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agegroup',
            name='code',
        ),
        migrations.RemoveField(
            model_name='agegroup',
            name='description',
        ),
        migrations.RemoveField(
            model_name='agegroup',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='agegroup',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='agegroup',
            name='min_age',
        ),
        migrations.RemoveField(
            model_name='civilstatus',
            name='code',
        ),
        migrations.RemoveField(
            model_name='civilstatus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='civilstatus',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='educationlevel',
            name='code',
        ),
        migrations.RemoveField(
            model_name='educationlevel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='educationlevel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='code',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='workstatus',
            name='code',
        ),
        migrations.RemoveField(
            model_name='workstatus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workstatus',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='youthclassification',
            name='code',
        ),
        migrations.RemoveField(
            model_name='youthclassification',
            name='description',
        ),
        migrations.RemoveField(
            model_name='youthclassification',
            name='is_active',
        ),
    ]
