# Generated by Django 5.2.6 on 2025-11-09 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0003_youthuser_shown_modals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='admin_user',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='youth_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youthprofiling.youthadmin'),
        ),
    ]
