# Generated by Django 5.2.6 on 2025-09-17 22:39

import django.db.models.deletion
import youthprofiling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0004_remove_agegroup_code_remove_agegroup_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ['-registration_date']},
        ),
        migrations.RenameField(
            model_name='eventregistration',
            old_name='attendance_status',
            new_name='agree_to_photos',
        ),
        migrations.RenameField(
            model_name='eventregistration',
            old_name='points_awarded',
            new_name='agree_to_terms',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='certificate_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='dietary_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='emergency_contact_name',
            field=youthprofiling.models.EncryptedField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='emergency_contact_number',
            field=youthprofiling.models.EncryptedField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='feedback_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='how_heard',
            field=models.CharField(blank=True, choices=[('social_media', 'Social Media'), ('friend', 'Friend'), ('email', 'Email'), ('website', 'Website'), ('community_board', 'Community Board'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='skills_interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='special_accommodations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'No Show')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='EventQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('radio', 'Single Choice'), ('checkbox', 'Multiple Choice'), ('dropdown', 'Dropdown')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('options', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='youthprofiling.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistrationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youthprofiling.eventquestion')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='youthprofiling.eventregistration')),
            ],
            options={
                'unique_together': {('registration', 'question')},
            },
        ),
    ]
