# Generated by Django 5.2.6 on 2025-11-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0006_auditlog_youth_user_alter_auditlog_admin_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('education', 'Education'), ('health', 'Health'), ('community', 'Community'), ('cultural', 'Cultural'), ('environment', 'Environment'), ('economic-empowerment', 'Economic Empowerment'), ('social-inclusion-and-equity', 'Social Inclusion and Equity'), ('peacebuilding-and-security', 'Peacebuilding and Security'), ('governance', 'Governance'), ('active-citizenship', 'Active Citizenship'), ('global-mobility', 'Global Mobility'), ('general', 'General')], max_length=50),
        ),
    ]
