# Generated by Django 5.2.6 on 2025-09-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0006_communityguideline_trendingtopic_communitypost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='event',
        ),
        migrations.RemoveField(
            model_name='communitypost',
            name='video',
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text Post'), ('image', 'Image Post')], default='text', max_length=10),
        ),
    ]
