# Generated by Django 5.2.6 on 2025-12-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0007_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('health', 'Health'), ('education', 'Education'), ('economic-empowerment', 'Economic Empowerment'), ('social-inclusion-and-equity', 'Social Inclusion and Equity'), ('peacebuilding-and-security', 'Peacebuilding and Security'), ('governance', 'Governance'), ('active-citizenship', 'Active Citizenship'), ('environment', 'Environment'), ('global-mobility', 'Global Mobility'), ('sports', 'Sports'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
