# Generated by Django 5.2.6 on 2025-09-19 11:49

import youthprofiling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0008_faq_callbackrequest_complaint_contactmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouthAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', youthprofiling.models.EncryptedField(max_length=100)),
                ('last_name', youthprofiling.models.EncryptedField(max_length=100)),
                ('middle_name', youthprofiling.models.EncryptedField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrator'), ('sk_chairman', 'SK Chairman'), ('sk_secretary', 'SK Secretary'), ('sk_treasurer', 'SK Treasurer'), ('sk_councilor', 'SK Councilor'), ('staff', 'Staff Member')], default='staff', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', youthprofiling.models.EncryptedField(max_length=15)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='admin_profiles/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_announcements', models.BooleanField(default=False)),
                ('can_manage_events', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_manage_settings', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Youth Administrator',
                'verbose_name_plural': 'Youth Administrators',
                'ordering': ['-date_joined'],
            },
        ),
    ]
