# Generated by Django 5.2.6 on 2025-12-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0008_alter_announcement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthuser',
            name='waitlist_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='youthuser',
            name='waitlist_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youthuser',
            name='waitlist_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youthuser',
            name='waitlist_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_info', 'Needs More Information')], max_length=20, null=True),
        ),
    ]
