# Generated by Django 5.2.6 on 2025-09-19 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0009_youthadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('registrations_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Registration Analytics',
                'verbose_name_plural': 'User Registration Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('participation_count', models.PositiveIntegerField(default=0)),
                ('date_recorded', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youthprofiling.event')),
            ],
            options={
                'verbose_name': 'Event Participation Analytics',
                'verbose_name_plural': 'Event Participation Analytics',
                'ordering': ['-date_recorded'],
            },
        ),
    ]
