# Generated by Django 5.2.6 on 2025-12-15 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0009_youthuser_waitlist_data_youthuser_waitlist_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('first_offense', 'First No-Show'), ('second_offense', 'Second No-Show'), ('deactivation_warning', 'Deactivation Warning')], max_length=20)),
                ('violation_date', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('event_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youthprofiling.eventregistration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_violations', to='youthprofiling.youthuser')),
            ],
            options={
                'verbose_name': 'Attendance Violation',
                'verbose_name_plural': 'Attendance Violations',
                'ordering': ['-violation_date'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('announcement', 'New Announcement'), ('event', 'New Event'), ('points', 'Points Earned'), ('registration', 'Registration Status'), ('attendance_warning', 'Attendance Warning'), ('deactivation_warning', 'Account Deactivation Warning'), ('system', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('points_change', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_announcement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youthprofiling.announcement')),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youthprofiling.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='youthprofiling.youthuser')),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
