# Generated by Django 5.2.6 on 2025-09-19 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0010_userregistrationanalytics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionKeyAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_key', models.CharField(max_length=255)),
                ('is_successful', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youthprofiling.youthadmin')),
            ],
            options={
                'verbose_name': 'Encryption Key Attempt',
                'verbose_name_plural': 'Encryption Key Attempts',
                'ordering': ['-timestamp'],
            },
        ),
    ]
