# Generated by Django 5.2.6 on 2025-09-20 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0011_encryptionkeyattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youthprofiling.youthadmin'),
        ),
    ]
