# Generated by Django 5.2.6 on 2025-09-20 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0012_alter_announcement_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youthprofiling.youthadmin'),
        ),
    ]
