# Generated by Django 5.2.6 on 2025-09-26 13:41

import youthprofiling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0013_eventregistration_rating_alter_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthuser',
            name='consent_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youthuser',
            name='parent_consent_letter',
            field=models.FileField(blank=True, null=True, upload_to='parent_consents/'),
        ),
        migrations.AddField(
            model_name='youthuser',
            name='parent_contact_number',
            field=youthprofiling.models.EncryptedField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='youthuser',
            name='parent_id_picture',
            field=models.ImageField(blank=True, null=True, upload_to='parent_ids/'),
        ),
        migrations.AddField(
            model_name='youthuser',
            name='parent_name',
            field=youthprofiling.models.EncryptedField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='youthuser',
            name='parent_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='youthuser',
            name='purok_zone',
            field=models.CharField(choices=[('AgnesVille', 'AgnesVille'), ('Bagong Bayan', 'Bagong Bayan'), ('Balon/Labajan', 'Balon/Labajan'), ('Cavite', 'Cavite'), ('Everlast Comp.', 'Everlast Comp.'), ('Josefina Subd.', 'Josefina Subd.'), ('Kamias I', 'Kamias I'), ('Kamias I-A', 'Kamias I-A'), ('Kamias II', 'Kamias II'), ('Kamias III', 'Kamias III'), ('Kapihan', 'Kapihan'), ('Kasoy I', 'Kasoy I'), ('Kasoy II', 'Kasoy II'), ('Labangan', 'Labangan'), ('Little Valley', 'Little Valley'), ('Mabolo', 'Mabolo'), ('Maligaya I-A', 'Maligaya I-A'), ('Maligaya I-B', 'Maligaya I-B'), ('Maligaya II', 'Maligaya II'), ('Marco Comp.', 'Marco Comp.'), ('Monte Carlo Homes', 'Monte Carlo Homes'), ('Munting-Pook', 'Munting-Pook'), ('Palomar Homes', 'Palomar Homes'), ('Ruhat III - Grotto', 'Ruhat III - Grotto'), ('Ruhat III- Lower', 'Ruhat III- Lower'), ('Ruhat III - Upper', 'Ruhat III - Upper'), ('Ruhat III -Upper A & B', 'Ruhat III -Upper A & B'), ('Ruhat IV', 'Ruhat IV'), ('Ruhat IV-A', 'Ruhat IV-A'), ('Ruhat V-Lower', 'Ruhat V-Lower'), ('Ruhat V-Upper', 'Ruhat V-Upper'), ('Salvador Drive', 'Salvador Drive'), ('San Rafael', 'San Rafael'), ('Sangley Comp.', 'Sangley Comp.'), ('Santos Comp.', 'Santos Comp.'), ('Shineville', 'Shineville'), ('Siruna PH.1', 'Siruna PH.1'), ('Siruna PH.2', 'Siruna PH.2'), ('Siruna PH.3', 'Siruna PH.3'), ('Siruna PH.4', 'Siruna PH.4'), ('Sitio Josefina', 'Sitio Josefina'), ('Soriano Comp.', 'Soriano Comp.'), ('Sucaben', 'Sucaben'), ('Summerville', 'Summerville'), ('Teremil Subd.', 'Teremil Subd.'), ('Tinago', 'Tinago')], default='AgnesVille', max_length=50),
        ),
    ]
