# Generated by Django 5.2.6 on 2025-09-26 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0014_youthuser_consent_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_user_id', models.IntegerField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archived_by', models.CharField(blank=True, max_length=150)),
                ('user_data', models.JSONField()),
                ('profile_picture_path', models.CharField(blank=True, max_length=500)),
                ('id_picture_path', models.CharField(blank=True, max_length=500)),
                ('birth_certificate_path', models.CharField(blank=True, max_length=500)),
                ('parent_consent_letter_path', models.CharField(blank=True, max_length=500)),
                ('parent_id_picture_path', models.CharField(blank=True, max_length=500)),
                ('deletion_reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'User Archive',
                'verbose_name_plural': 'User Archives',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('login_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.TextField(blank=True)),
                ('youth_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youthprofiling.youthuser')),
            ],
            options={
                'verbose_name': 'User Log',
                'verbose_name_plural': 'User Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
