# Generated by Django 5.2.6 on 2025-09-26 19:11

import youthprofiling.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0016_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=youthprofiling.models.EncryptedField(max_length=6),
        ),
    ]
