# Generated by Django 5.2.6 on 2025-09-26 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0017_alter_otpverification_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 Star - Poor'), (2, '2 Stars - Fair'), (3, '3 Stars - Good'), (4, '4 Stars - Very Good'), (5, '5 Stars - Excellent')])),
                ('comments', models.TextField(blank=True, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('would_attend_again', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='youthprofiling.eventregistration')),
            ],
            options={
                'verbose_name': 'Event Evaluation',
                'verbose_name_plural': 'Event Evaluations',
                'ordering': ['-created_at'],
            },
        ),
    ]
