# Generated by Django 5.2.6 on 2025-10-23 08:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0018_eventevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='APKVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('file_size', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('release_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'apk_versions',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='DownloadAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_downloads', models.PositiveIntegerField(default=0)),
                ('mobile_downloads', models.PositiveIntegerField(default=0)),
                ('desktop_downloads', models.PositiveIntegerField(default=0)),
                ('tablet_downloads', models.PositiveIntegerField(default=0)),
                ('qr_code_downloads', models.PositiveIntegerField(default=0)),
                ('direct_downloads', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'download_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='APKDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('device_brand', models.CharField(blank=True, max_length=100)),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('os_name', models.CharField(blank=True, max_length=50)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('browser_name', models.CharField(blank=True, max_length=100)),
                ('browser_version', models.CharField(blank=True, max_length=50)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_tablet', models.BooleanField(default=False)),
                ('is_desktop', models.BooleanField(default=False)),
                ('download_method', models.CharField(choices=[('direct', 'Direct Download'), ('qr_code', 'QR Code'), ('button', 'Download Button')], default='direct', max_length=20)),
                ('download_source', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'apk_downloads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='apk_downloa_created_54352f_idx'), models.Index(fields=['ip_address'], name='apk_downloa_ip_addr_e5d26b_idx'), models.Index(fields=['device_type'], name='apk_downloa_device__f6cfb5_idx')],
            },
        ),
    ]
