# Generated by Django 5.2.6 on 2025-10-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youthprofiling', '0019_apkversion_downloadanalytics_apkdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadanalytics',
            name='button_downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
